language: scala

# only trigger builds on master
branches:
  only:
    - master

script:
  - sbt +clean +coverage +test

before_install:
  - pip install codecov --user codecov

after_install:
  - codecov
